version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
